# grog.package
package_list:
  name:
    - sl
    - mosh
    - git
    - tmux
    - nfs-common
    - network-manager
    - avahi-daemon
    - jq
    - ca-certificates
    - dbus
    - unzip

# geerlingguy.pip
pip_install_packages:
  - docker

# geerlingguy.docker
docker_users:
  - '{{ default_user_name }}'
  - '{{ ci_user }}'
