# grog.package
package_list:
  name:
    - sl
    - mosh
    - qemu-guest-agent

# geerlingguy.pip
pip_install_packages:
  - docker

# geerlingguy.docker
docker_users:
  - '{{ default_user_name }}'
  - '{{ ci_user }}'
