---
  - name: create influxdb container directory on localhost
    file:
      path: /mnt/cephfs/influxdb
      state: directory

  - name: copy ceph files
    copy: src=../files/{{ item }} dest=/etc/ceph/
    with_items:
      - ceph.client.admin.keyring
      - ceph.conf

  - name: mount cephfs
    ansible.posix.mount:
      src: '{{ cephfs_mount_src_influxdb }}'
      path: /mnt/cephfs/influxdb
      state: mounted
      opts: '{{ cephfs_mount_opts }}'
      fstype: ceph

  - name: create influxdb container directory on cephfs
    file:
      path: /mnt/cephfs/influxdb/config
      state: directory

  - name: create influxdb container directory on cephfs
    file:
      path: /mnt/cephfs/influxdb/data
      state: directory

  - name: create a influxdb container
    community.general.docker_container:
      name: influxdb-1
      image: influxdb
      pull: true
      volumes:
        - /mnt/cephfs/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        - /mnt/cephfs/influxdb/data:/var/lib/influxdb
      env:
        TZ: 'America/New_York'
        INFLUXDB_ADMIN_USER: '{{ influxdb_admin_user }}'
        INFLUXDB_ADMIN_PASSWORD: '{{ influxdb_admin_password }}'
      ports:
        - '2003:2003'
        - '8088:8088'
        - '8086:8086'
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: '5'
      restart_policy: unless-stopped
      container_default_behavior: no_defaults
      state: started

  - name: create homeassistant database
    community.general.influxdb_database:
        database_name: 'homeassistant'

  - name: create pfsense database
    community.general.influxdb_database:
        database_name: 'pfsense'

  - name: create homeassistant influxdb user
    community.general.influxdb_user:
      user_name: '{{ homeassistant_influxdb_username }}'
      user_password: '{{ homeassistant_influxdb_password }}'

  - name: create pfsese influxdb user
    community.general.influxdb_user:
      user_name: '{{ pfsense_influxdb_username }}'
      user_password: '{{ pfsense_influxdb_password }}'
