---
  - name: create influxdb container directory on localhost
    file:
      path: /mnt/cephfs/influxdb
      state: directory

  - name: copy ceph files
    copy: src=../files/{{ item }} dest=/etc/ceph/
    with_items:
      - ceph.client.admin.keyring
      - ceph.conf

  - name: mount cephfs
    ansible.posix.mount:
      src: '{{ cephfs_mount_src_influxdb }}'
      path: /mnt/cephfs/influxdb
      state: mounted
      opts: '{{ cephfs_mount_opts }}'
      fstype: ceph

  - name: create influxdb container directory on cephfs
    file:
      path: /mnt/cephfs/influxdb/config
      state: directory

  - name: create influxdb container directory on cephfs
    file:
      path: /mnt/cephfs/influxdb/data
      state: directory

  - name: create a influxdb container
    community.general.docker_container:
      name: influxdb-1
      image: influxdb
      volumes:
        - /mnt/cephfs/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        - /mnt/cephfs/influxdb/data:/var/lib/influxdb
      env:
        TZ: 'America/New_York'
        PUID: '1000'
        GUID: '1000'
      ports:
        - '8086:8086'
        - '2003:2003'
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: 5
      restart_policy: unless-stopped
      container_default_behavior: no_defaults
      state: started
