---
  - name: create code container settings directory
    file:
      path: /opt/vs-code
      state: directory

  - name: create git directory
    file:
      path: /home/{{ default_user_name }}/git
      state: directory

  - name: create a code container
    community.general.docker_container:
      name: code-1
      image: linuxserver/code-server:latest
      pull: true
      volumes:
        - /home/{{ default_user_name }}/git:/git
        - /opt/vs-code:/config
      env:
        TZ: "America/New_York"
      ports:
        - "8443:8443"
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: '5'
      restart_policy: unless-stopped
      container_default_behavior: no_defaults
      state: started
