---
roles:
  - ironicbadger.ansible_users
  - grog.package
  - geerlingguy.security
  - geerlingguy.ntp
  - geerlingguy.docker
  - geerlingguy.pip


collections:
  - community.general
  - ansible.posix
  - community.mysql
