---
  - name: create mariadb container database directory
    file:
      path: /opt/mariadb/databases
      state: directory

  - name: create mariadb container config directory
    file:
      path: /opt/mariadb/config
      state: directory

  - name: create a mariadb container
    community.general.docker_container:
      name: mariadb-1
      image: linuxserver/mariadb:latest
      volumes:
        - /opt/mariadb/databases:/config/databases
        - /opt/mariadb/config:/config
      env:
        TZ: 'America/New_York'
        DATADIR: '/config/databases'
        LANG: 'en_US.UTF-8'
        LANGUAGE: 'en_US.UTF-8'
        MYSQL_DIR: '/config'
        MYSQL_ROOT_PASSWORD: '{{ mariadb_root_password }}'
        MYSQL_USER: '{{ mariadb_user }}'
        MYSQL_PASSWORD: '{{ mariadb_password }}'
      ports:
        - "3306:3306"
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: '5'
      restart_policy: unless-stopped
      container_default_behavior: no_defaults
      state: started

  - name: delete anonymous user accounts
    community.mysql.mysql_user:
      name: ''
      host_all: yes
      state: absent

  - name: create nginx proxy db
    community.mysql.mysql_db:
      name:
        - nginx_proxy
        - homeassistant
        - nextcloud
      state: present

  - name: create nginx_proxy user
    community.mysql.mysql_user:
      name: '{{ nginx_proxy_username }}'
      password: '{{ nginx_proxy_password }}'
      priv: 'nginx_proxy.*:ALL'
      host: '%'
      state: present

  - name: create homeassistant user
    community.mysql.mysql_user:
      name: '{{ homeassistant_username }}'
      password: '{{ homeassistant_password }}'
      priv: 'homeassistant.*:ALL'
      host: '%'
      state: present

  - name: create nextcloud user
    community.mysql.mysql_user:
      name: '{{ nextcloud_username }}'
      password: '{{ nextcloud_password }}'
      priv: 'nextcloud.*:ALL'
      host: '%'
      state: present
