---
  - name: create docker-registry container directory on localhost
    file:
      path: /mnt/cephfs/docker-registry
      state: directory

  - name: copy ceph files
    copy: src=../files/{{ item }} dest=/etc/ceph/
    with_items:
      - ceph.client.admin.keyring
      - ceph.conf

  - name: mount cephfs
    ansible.posix.mount:
      src: '{{ cephfs_mount_src_docker_registry }}'
      path: /mnt/cephfs/docker-registry
      state: mounted
      opts: '{{ cephfs_mount_opts }}'
      fstype: ceph

  # - name: create docker-registry container directory on cephfs
  #   file:
  #     path: /mnt/cephfs/docker-registry/config
  #     state: directory

  - name: create docker-registry container directory on cephfs
    file:
      path: /mnt/cephfs/docker-registry/data
      state: directory

  - name: create a docker-registry sync container
    community.general.docker_container:
      name: docker-registry-1
      image: registry:latest
      volumes:
        - /mnt/cephfs/docker-registry/data:/var/lib/registry
      env:
        TZ: 'America/New_York'
        PUID: '1000'
        GUID: '1000'
        REGISTRY_PROXY_REMOTEURL: 'https://registry-1.docker.io'
        DELETE: 'true'
      ports:
        - '8080:5000'
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: '5'
      restart_policy: unless-stopped
      container_default_behavior: no_defaults
      state: started
